### ISSUE TITLE
Failed `audit` check for `json`

### ISSUE THREAD

**Issue by Kijewski** [askama-rs/askama_playground#6]
Hm, [`json`](https://crates.io/crates/json) fails the audit check. The audit action [`actions-rs/audit-check@v1`](https://github.com/actions-rs/audit-check) is deprecated and does not work well anymore, so the error was only found after PR #5 was merged.

- [x] need to switch to [`EmbarkStudios/cargo-deny-action@v1`](https://github.com/EmbarkStudios/cargo-deny-action)
- [x] the audit warning should be fixed or suppressed

Do you want to do the latter, @GuillaumeGomez? [RUSTSEC-2022-0081](https://rustsec.org/advisories/RUSTSEC-2022-0081) mentions e.g. [`jzon`](https://crates.io/crates/jzon).

**Comment by GuillaumeGomez** [comment]
Arf indeed. And sure, let's give it a try.

**Comment by Kijewski** [comment]
Fixed.
