### ISSUE TITLE
Add a "share code" button

### ISSUE THREAD

**Issue by GuillaumeGomez** [askama-rs/askama_playground#9]
I've been looking into this and I'm not sure how to do it. We could compress both source codes and generate URL parameters in base64 I suppose. Do you have a better idea maybe @Kijewski ?

**Comment by Kijewski** [comment]
It should be possible to [register an Oauth app](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app), so we can write Gists for the user (once they allow it). I looked into it and I find Oauth massively complicated, but maybe I'm just stupid. :)

**Comment by GuillaumeGomez** [comment]
I wrote an OAuth2 implementation 7 years ago in an afternoon. It's actually super simple with the right explanations. You just need to find the right explanation. In short (well, actually it's literally just that):

 1. You ask the website an authorization token (that's where the user logs in and say if they want to give you access)
 2. You use the authorization token to ask the website an access token.
 3. You then query the information you want using the access token.

I have a small implementation in python [here](https://github.com/GuillaumeGomez/merge-bot/blob/afd7724ba29a184c3ad651ab01ff7bf848e0705f/ultron/index.py#L126) (well, it starts from this function, but I'll let you take a look if you're interested).

Anyway, I don't think storing content into gist or anywhere is a good idea here. Compression then base64 in URL should be enough I think. ^^'

**Comment by Kijewski** [comment]
Oauth itself is OK if you're actually using it on server-side, but in here I would have liked to keep everything on the client-side, so the browser would get the bearer-token, and talk with github, without any middle-man.

**Comment by GuillaumeGomez** [comment]
That's one more argument in favor to not use oauth or any external service. ;)

**Comment by Kijewski** [comment]
Implemented in #11.
